version: '3.8'

services:
  tests:
    image: tests
    build: 
      context: .
      target: tests
    environment:
      - FASTA=tests/fixtures/Homo_sapiens.GRCh38.dna.chromosome.X.Y.fa
      - REFGENE=tests/fixtures/genes.refGene
    command: ["pytest", "-m", "not http and not db"]
