version: '3.8'

services:
  tests:
    image: tests
    build: 
      context: .
      target: tests
    environment:
      - FASTA=tests/fixtures/chrX.fa
      - REFGENE=tests/fixtures/genes.refGene
