name: PullRequest

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
    - uses: actions/checkout@v3
    
    - name: Download refGene (sample dataset for tests)
      run: ./download_refGene.sh -hg38_sample

    - name: Build Tests
      run: run-tests.sh
