name: publish_to_dockerhub

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  publish_to_dockerhub:
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
    - uses: actions/checkout@v3
    
    - name: Download refGene (sample dataset for tests)
      run: ./download_refGene.sh -hg38_sample

    - name: Run tests
      run: ./run-tests.sh

    - name: Cleanup
      run: |
        echo "Removing test fixtures"
        rm -f tests/fixtures/Homo_sapiens.GRCh38.dna.chromosome.X.fa*
        rm -f tests/fixtures/genes.refGene
        rm -f tests/fixtures/LRG_RefSeqGene
    
    - name: Download refGene
      run: ./download_refGene.sh -hg38

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images:  ${{ vars.DOCKERHUB_USERNAME }}/hgvs
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
 
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}